### ISSUE TITLE
Not working with recent libraries

### ISSUE THREAD

**Issue by ConfidantCommunications** [Tiago-Ling/FlxIsoTilemap#16]
Hi Tiago,
I was able to successfully compile the demo but after selecting one of the three buttons, I just get a black screen. This is true for both html5 and flash targets. Here are my current libraries:

flixel-addons: 1.0.0 1.0.1 1.1.0 1.1.1 2.0.0 [2.1.0]
flixel-tools: [1.2.0]
flixel: 3.0.0-alpha 3.0.4 3.2.2 3.3.11 3.3.12 3.3.4 3.3.5 3.3.6 3.3.8 4.0.1 [4.1.1]

lime-tools: 1.3.1 1.4.0 1.5.6 [1.5.7]
lime: 0.9.2 0.9.4 0.9.6 0.9.7 1.0.0 1.0.1 2.1.3 2.3.3 2.4.2 2.4.4 2.7.0 2.9.0 [2.9.1] 3.1.0

openfl-html5-dom: 1.1.0 1.2.0 1.2.1 [1.2.2]
openfl-html5: [1.0.5] 1.1.0-beta 1.4.0-beta 1.4.2-beta
openfl-native: 1.1.1 1.2.2 1.3.0 [1.4.0]
openfl-samples: 1.1.0 1.2.1 1.3.0 2.1.0 2.2.2 [3.3.1]
openfl: 1.1.0 1.1.1 1.2.2 1.2.3 1.3.0 1.4.0 2.0.0 2.0.1 2.1.5 2.2.4 2.2.8 3.0.3 3.0.8 3.1.0 3.4.0 3.6.0 [3.6.1] 4.1.0

Any thoughts? Thanks.

**Comment by Tiago-Ling** [comment]
Hi Allan,

Unfortunately there's no support for Flash and HTML5 at the moment, just cpp (desktop) and neko.

It's been a while since i had time to work on this lib, but i hope to soon be able to continue contributing 

Btw a Flash / HTML5 renderer won't be hard to implement, it'll probably be very similar to what we have now, just switching the drawTiles part by traditional blitting (as is the case in FlxTilemap).

There's already a related issue, see #10

**Comment by ConfidantCommunications** [comment]
Thanks!
